services:
  metatrader:
    image: p3ps1man/dockertrader-vnc
    container_name: mt5
    environment:
      - VNC_PASSWORD=123 
    ports:
      - "3000:3000"
    volumes:
      - app:/home/mt5/program/
volumes:
  app: